### ISSUE TITLE
What is the API call limit per day?

### ISSUE THREAD

**Issue by CeleritasCelery** [codecoll/feedly#3]
I see in the code that you can hit a limit where you make too many API calls in a single day. What is that limit and is it an issue with normal usage?

**Comment by codecoll** [comment]
It's 250 per day. It's not an issue for me. It can be an issue if one reads hundreds of items a day (that is, actually reads each of them, not just scans the list of titles for interesting things), because every time an item is opened the code sends a "mark as read" command to the api.

https://developer.feedly.com/v3/#rate-limiting

**Comment by CeleritasCelery** [comment]
Thanks
